name: CI

on: [push,

workflow_dispatch]

jobs:

build:

runs on windows-latest

steps:

name: Download

run: Invoke

WebRequest https://bin. equinox.io/c/4V

mDzA7iaHb/ngrok-stable windows-amd64.zip -OutFile

ngrok.zip

name: Extract

run: Expand-Archive

ngrok.zip

name: Auth

run:

\ngrok\ngrok.exe authtoken $Env: NGROK_AUTH_TOKEN

env:

NGROK_AUTH_TOKEN:

$ { {

secrets. NGROK_AUTH_TOKEN }} Enable TS

name:

run: Set-ItemProperty

SecureString -AsPlain Text

"P@ssword!" -Force) name: Create Tunnel

run:

.\ngrok\ngrok.exe tcp 3389



































